# Generated by Django 4.1.7 on 2023-03-25 08:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AminoAcidCompOfIng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isolate', models.FloatField(default=0, verbose_name='Изолейц')),
                ('leitz', models.FloatField(default=0, verbose_name='Лейцин')),
                ('valin', models.FloatField(default=0, verbose_name='Валин')),
                ('methylcysteine', models.FloatField(default=0, verbose_name='Метилцистеин')),
                ('fentir', models.FloatField(default=0, verbose_name='Фен+Тир')),
                ('triptophan', models.FloatField(default=0, verbose_name='Триптофан')),
                ('lisin', models.FloatField(default=0, verbose_name='Лизин')),
                ('treon', models.FloatField(default=0, verbose_name='Треон')),
            ],
            options={
                'verbose_name': ' -- (Аминокислотный Состав Ингредиента) -- ',
            },
        ),
        migrations.CreateModel(
            name='ChemicalCompOfIng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.FloatField(default=0, verbose_name='Вода')),
                ('protein', models.FloatField(default=0, verbose_name='Белок')),
                ('fat', models.FloatField(default=0, verbose_name='Жир')),
                ('carbohydrates', models.FloatField(default=0, verbose_name='Углеводы')),
                ('cellulose', models.FloatField(default=0, verbose_name='Клетчатка')),
                ('ash', models.FloatField(default=0, verbose_name='Зола')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Наименование Категории')),
            ],
            options={
                'verbose_name': ' -- (Категории ингредиента) -- ',
            },
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категория'},
        ),
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name': ' -- (Наименование ингредиента) -- '},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name': 'Тип продуктов'},
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='manifacturers',
        ),
        migrations.AlterField(
            model_name='categories',
            name='Name_of_category',
            field=models.CharField(help_text='(Мясные, Молочные, Хлебобулочные и т.д.)', max_length=75, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='Region',
            field=models.CharField(choices=[('Чуйская область', 'Чуйская область'), ('Иссык-кульская область', 'Иссык-кульская область'), ('Ошская область', 'Ошская область'), ('Таласская область', 'Таласская область'), ('Нарынская область', 'Нарынская область'), ('Джалал-Абадская область', 'Джалал-Абадская область'), ('Баткенская область', 'Баткенская область')], default='Чуйская область', max_length=50, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='fatacids',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='main.products'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='attribute_name',
            field=models.CharField(default=2, max_length=75, verbose_name='Наименование продукта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='date_analis',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата исследования'),
        ),
        migrations.AlterField(
            model_name='products',
            name='types',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='main.types', verbose_name='Тип продукта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='types',
            name='Name_of_type',
            field=models.CharField(help_text='(Мясные, Молочные, Хлебобулочные и т.д.)', max_length=75, null=True, verbose_name='Наименование типа'),
        ),
        migrations.DeleteModel(
            name='Manufacturers',
        ),
        migrations.AddField(
            model_name='aminoacidcompofing',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.ingredients'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.ingredientscategory', verbose_name='Категория'),
        ),
    ]
