# Generated by Django 4.1.7 on 2023-03-28 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aminoacidcompofing_chemicalsingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.categories', verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='IngredientsCategory',
        ),
    ]
