# Generated by Django 4.1.7 on 2023-03-25 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aminoacidcompofing_chemicalcompofing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalcompofing',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.ingredients'),
        ),
    ]
