# Generated by Django 4.1.7 on 2023-03-25 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_chemicalcompofing_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='FatAcidsIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_acid', models.CharField(choices=[('Насыщенные жирные кислоты, %', 'Насыщенные жирные кислоты, %'), ('Мононенасыщенные жирные кислоты, %', 'Мононенасыщенные жирные кислоты, %'), ('Полиненасыщенные жирные кислоты, %', 'Полиненасыщенные жирные кислоты, %')], default='Насыщенные жирные кислоты, %', max_length=75, verbose_name='Тип ж-кислоты')),
                ('value', models.FloatField(verbose_name='Содержание')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.ingredients')),
            ],
            options={
                'verbose_name': ' -- (Виды Жирнокислоты) -- ',
            },
        ),
        migrations.CreateModel(
            name='ChemicalsIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluable_solids', models.FloatField(default=0, verbose_name='Массовая доля растворимых сухих веществ, %')),
                ('ascorbic_acids', models.FloatField(default=0, verbose_name='Массовая доля аскорбиновой кислоты, г/дм3')),
                ('ash_content', models.FloatField(default=0, verbose_name='Зольность, %')),
                ('moisture', models.FloatField(default=0, verbose_name='Массовая доля влаги, %')),
                ('protein', models.FloatField(default=0, verbose_name='Массовая доля белка, %')),
                ('fat', models.FloatField(default=0, verbose_name='Массовая доля жира, %')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.ingredients')),
            ],
            options={
                'verbose_name': ' -- (Химический состав) -- ',
            },
        ),
    ]
