# Generated by Django 4.1.7 on 2023-03-26 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_fatacidsingredients_chemicalsingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='MineralsIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ca', models.FloatField(default=0, verbose_name='Ca (Кальций)')),
                ('Na', models.FloatField(default=0, verbose_name='Na (Натрий)')),
                ('K', models.FloatField(default=0, verbose_name='K (Калий)')),
                ('P', models.FloatField(default=0, verbose_name='P (Фосфор)')),
                ('Mn', models.FloatField(default=0, verbose_name='Mn (Марганец)')),
                ('Zn', models.FloatField(default=0, verbose_name='Zn (Цинк)')),
                ('Se', models.FloatField(default=0, verbose_name='Se (Скандий)')),
                ('Cu', models.FloatField(default=0, verbose_name='Cu (Медь)')),
                ('Fe', models.FloatField(default=0, verbose_name='Fe (Железо)')),
                ('I', models.FloatField(default=0, verbose_name='I (Йод)')),
                ('B', models.FloatField(default=0, verbose_name='B (Бор)')),
                ('Li', models.FloatField(default=0, verbose_name='Li (Литий)')),
                ('Al', models.FloatField(default=0, verbose_name='Al (Алюминий)')),
                ('Mg', models.FloatField(default=0, verbose_name='Mg (Магний)')),
                ('V', models.FloatField(default=0, verbose_name='V (Ванадий)')),
                ('Ni', models.FloatField(default=0, verbose_name='Ni (Нитрий)')),
                ('Co', models.FloatField(default=0, verbose_name='Co (Ковальт)')),
                ('Cr', models.FloatField(default=0, verbose_name='Cr (Хром)')),
                ('Sn', models.FloatField(default=0, verbose_name='Sn (Олово)')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.ingredients')),
            ],
            options={
                'verbose_name': ' -- (Минеральный состав) -- ',
            },
        ),
        migrations.DeleteModel(
            name='ChemicalCompOfIng',
        ),
    ]
